blank_issues_enabled: false
contact_links:
  - name: Support group for discussions
    url: https://discord.me/oscbr
    about: Please ask (and answer) questions here, use the issue tracker only for issues.
